/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "notificaciones.h"

bool_t
xdr_nodo_hamburguesa2 (XDR *xdrs, nodo_hamburguesa2 *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pedido2 (XDR *xdrs, pedido2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->mesa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pedido_hamburguesas, MAX_PEDIDO,
		sizeof (nodo_hamburguesa2), (xdrproc_t) xdr_nodo_hamburguesa2))
		 return FALSE;
	return TRUE;
}
