/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pedidos.h"
#include <stdio.h>

empresa *
consultarempresa_3_svc(void *argp, struct svc_req *rqstp)
{
	static empresa  result;
	printf("\nConsultando informacion empresa...");

	fflush(stdout);
	FILE* fichero;
	fichero = fopen("/home/daniel/Documentos/Lab_Distribuidos/Lab_SD_Hamrguesas/servidor_pedidos/datosEmpresa.txt", "rt");
	if(fichero == NULL ) {
		printf("No fue posible abrir el archivo\n");
		return NULL;
   }
	fgets(result.nombreEmpresa,MAXNOM,fichero);
	fgets(result.NIT,MAXNOM,fichero);
	printf("\nEnviando respuesta datos empresa...");
	fflush(stdout);
	return &result;
}

listaProductos *
consultarproductos_3_svc(void *argp, struct svc_req *rqstp)
{
	static listaProductos  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
registrarpedidosistema_3_svc(pedido1 *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
