/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pedidos.h"
#include "notificaciones.h"
#include <stdio.h>



empresa *
consultarempresa_3_svc(void *argp, struct svc_req *rqstp)
{
	static empresa  result;
	printf("\nConsultando informacion empresa...");
	fflush(stdout);

	FILE* fichero;
	fichero = fopen("datosEmpresa.txt", "rt");
	if(fichero == NULL ) {
		printf("No fue posible abrir el archivo\n");
		return NULL;
   }
	fgets(result.nombreEmpresa,MAXNOM,fichero);
	fgets(result.NIT,MAXNOM,fichero);
	printf("\nEnviando respuesta datos empresa...");
	fflush(stdout);

	fclose(fichero);
	return &result;
}

listaProductos *
consultarproductos_3_svc(void *argp, struct svc_req *rqstp)
{
	static listaProductos  result;
	FILE* fichero;
	printf("\nConsultando informacion productos...");
	fflush(stdout);
	//Abro el archivo
	fichero = fopen("datosHamburguesa.txt", "rt");
	
	//Verifico si fue posible abrirlo
	if(fichero == NULL ) {
		printf("No fue posible abrir el archivo\n");
		fflush(stdout);
		return NULL;
   	}


	
	//Obtengo los datos del fichero
	char temp2[30];
	char aux;
	int cont=0;
	//int i=0;
	int j=0;

	while(!feof(fichero)){
		//limpio la variable temporal
		aux='\0';
		char temp[30];
		for(j=0;aux!='-';j++){
			aux=fgetc(fichero);
			if(aux!='-'&&aux!='\0'){
				temp[j]=aux;
			}
			temp[j+1]='\0';
		}
		//Copio el nombre del producto
		strcpy(result.product[cont].nombreIngrediente,temp);
		fflush(stdout);
		fgets(temp,30,fichero);
		//Elimino el salto de linea de la variable temporal
		
		for(int k=0;k<30;k++){
			if(k=='\n'){
				temp[k]='\0';
			}			
		}
		
		//Copio el valor del producto
		result.product[cont].valor=atof(temp);
		cont++;

	}
	
	
	fclose(fichero);



	printf("\nEnviando informacion productos...");
	fflush(stdout);
	return &result;
}

bool_t *
registrarpedidosistema_3_svc(pedido1 *argp, struct svc_req *rqstp)
{
	
	printf("\nRegistrando pedido...");
	fflush(stdout);
	static bool_t  result;

	if (argp==NULL){
		printf("\n	Error me llego un pedido nulo");
		fflush(stdout);
		result=0;
	}else{
		char *host="localhost";
		CLIENT *clnt;
		bool_t  *result_1;
		pedido2  notificarpedidosistema_1_arg;

	#ifndef	DEBUG
		clnt = clnt_create (host, notificacion_hamburguesas, notificacion_hamburguesas_version, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			printf("Error de conexion con el servidor de notificaciones...");
			fflush(stdout);
			result=0;
			return &result;
		}
	#endif	/* DEBUG */
		for(int i=0;i<MAX_PEDIDO;i++){
			if(((*argp).pedido_hamburguesas[i].tipo=='m')||
			((*argp).pedido_hamburguesas[i].tipo=='g')||
			((*argp).pedido_hamburguesas[i].tipo=='p')){
				printf("\nEnviando hamburgesa (%s) al servidor notificaciones\n",(*argp).pedido_hamburguesas[i].identificador);
				fflush(stdout);
				notificarpedidosistema_1_arg.pedido_hamburguesas[i].tipo=(*argp).pedido_hamburguesas[i].tipo;
				notificarpedidosistema_1_arg.pedido_hamburguesas[i].cantidadIngredientesExtra=(*argp).pedido_hamburguesas[i].cantidadIngredientesExtra;
			}
		}
		result_1 = notificarpedidosistema_1(&notificarpedidosistema_1_arg, clnt);
		if ((result_1 == (bool_t *) NULL)||(result_1==0)) {
			printf("Error de conexion con el servidor de notificaciones...");
			clnt_perror (clnt, "call failed");
			fflush(stdout);
			result=0;
		}else{
			printf("Se notifico con exito...");
			result=1;
		}
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
	}

	return &result;
}
