/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pedidos.h"
#include <stdio.h>

//Variable que contiene el precio de las tres hamburgesas del menu
producto burgersBase[3];
int pedidoPagado=0;
int posBurger=0;
pedido1  registrarpedidosistema_3_arg;


/**
 *Funcion que se encarga de consultar los valores de las hamburgusas 
 * Entradas: 
 * Salidas:
 */ 
int cargarValoresHamburguesas(CLIENT *clnt);
/**
 * funcion void que consulta los datos de la empresa del servidor
 * entradas: CLIENT
 * salidas:
 */
void datosEmpresa(CLIENT *clnt);
/**
 * funcion void que permite comprar hamburgesas
 * entradas: 
 * salidas:
 */
void comprarHamburgesas(); 
int existeHamburguesa(char *identificador);
float consultarValorBurger(char tipo);

/**
 * procedimiento que imprime la lista de las hamburgesas ordenadas hasta el momento
 * entradas
 * salidas 
 */
void listarBurgersPedidas();
/**
 * funcion void que consulta los datos de los productos del servidor
 * entradas: CLIENT
 * salidas:
 */
void datosProductos(CLIENT *clnt);


/**
 * procedimiento void que me permite modificar una hamburguesa
 * entradas:
 * salidas:
 */
void editarHamburguesa();

/**
 * procedimiento void eliminar hamburguesa
 * entrada:
 * salida
 */
void eliminarHamburguesa();

/**
 * procedimiento void que permite visualizar los detalles de la factura hamburguesa
 * entrada:
 * salida
*/
void mostrarFactura(char *factura);

/**
 * procedimiento void que permite pegar la factura y enviar el pedido al servidor
 * entrada:CLIENT
 * salida
 */

void pagarPedido(CLIENT *clnt,char *factura);


void
gestion_hamburguesas_3(char *host)
{
	CLIENT *clnt;
	//Variables locales
	int opcion=0;


//Se intenta la conexion con el servidor pedidos
#ifndef	DEBUG
	clnt = clnt_create (host, gestion_hamburguesas, gestion_hamburguesas_version, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		printf("Error conectando al servidor...\n");
		exit (1);
	}
#endif	/* DEBUG */

	//Se cargan los valores de las hamburgesas

	if(cargarValoresHamburguesas(clnt)==0){
		printf("	Lo sentimos no se pudieron cargar los precios de las hamburgesas\n");
		exit (1);
	}
	
	//Se imprime el menu de opciones

	do{
		printf("\n-----------Menu de pedidos----------\n");
		printf("1. Mostrar datos de la empresa\n");
		printf("2. Comprar hamburguesa \n");
		printf("3. Modificar compra de haburguesa\n");
		printf("4. Eliminar hamburguesa del pedido\n");
		printf("5. Listar hamburguesas pedidas\n");
		printf("6. Mostrar factura y pagar pedido\n");
		printf("7. Salir\n\n");

		printf("\n Digite opcion: ");
		scanf("\%d", &opcion);

		switch(opcion){
			case 1:
				//consulto la empresa
				printf("	Informacion Empresa\n");
				datosEmpresa(clnt);
				printf("	Informacion de los productos");
				datosProductos(clnt);
			
			break;			
				
			case 2:
				//Comprar Hamburguesas
				comprarHamburgesas();
			
			break;
			
			case 3:
				//Editar hamburgesa
				editarHamburguesa();
			break;

			
			case 4:
				//Eliminar Hamburguesa
				eliminarHamburguesa();
				
			break;
			


			case 5:
				//Listar hamburgesas pedidas
				listarBurgersPedidas();
			break;

			
			case 6:
				if(posBurger>0){
					//Generar factura y pagar
					
					char factura[300];
					strcpy(factura,"");
					mostrarFactura(factura);
					getchar();
					char pagar;
					printf("\n%s \n",factura);
					printf("\nDesea pagar el pedido y/n: ");
					scanf("%c",&pagar);
					getchar();

					if((pagar=='y'||pagar=='Y')&&pedidoPagado==0){
						//Pagar
						
						pagarPedido(clnt,factura);
					}

				}else{
					printf("\n	No se han comprado hamburgesas aun...\n");
				}
				
				
			break;
			
			case 7:
				//Se desconecta del servidor pedidos
				#ifndef	DEBUG
					clnt_destroy (clnt);
				#endif	 /* DEBUG */
				printf("\nAdios cliente...\n");
				break;
			}
				
				
			
			

	}while(opcion!=7);

}


int main (int argc, char *argv[]){
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_hamburguesas_3 (host);
exit (0);
}

int cargarValoresHamburguesas(CLIENT *clnt){
	int respuesta;

	listaProductos  *result_2;
	char *consultarproductos_3_arg;
	result_2 = consultarproductos_3((void*)&consultarproductos_3_arg, clnt);
	if (result_2 == (listaProductos *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	int i=0;
	int banderaHecho=0;
	while(i<CANTIDAD_PRODUCTOS&&result_2->product[i].valor!=0&&banderaHecho<3){
		if((strcmp("Hamburguesa Pequenia", result_2->product[i].nombreIngrediente))==0){
			strcpy(burgersBase[0].nombreIngrediente,result_2->product[i].nombreIngrediente);
			burgersBase[0].valor=result_2->product[i].valor;
			banderaHecho++;
		}else if((strcmp("Hamburguesa Mediana", result_2->product[i].nombreIngrediente))==0){
			strcpy(burgersBase[1].nombreIngrediente,result_2->product[i].nombreIngrediente);
			burgersBase[1].valor=result_2->product[i].valor;
			banderaHecho++;
		}else if((strcmp("Hamburguesa Grande", result_2->product[i].nombreIngrediente))==0){
			strcpy(burgersBase[2].nombreIngrediente,result_2->product[i].nombreIngrediente);
			burgersBase[2].valor=result_2->product[i].valor;
			banderaHecho++;
		}
		i++;
	}

	return respuesta;
}



void datosEmpresa(CLIENT *clnt){

	char *consultarempresa_3_arg;
	empresa  *result_1;

	result_1 = consultarempresa_3((void*)&consultarempresa_3_arg, clnt);
	if (result_1 == (empresa *) NULL) {
		clnt_perror (clnt, "call failed...\n");
		return;
	}

	printf("	Empresa: %s",(result_1)->nombreEmpresa);
	printf("	NIT: %s\n",(result_1)->NIT);



}

void datosProductos(CLIENT *clnt){
	listaProductos  *result_2;
	char *consultarproductos_3_arg;
	result_2 = consultarproductos_3((void*)&consultarproductos_3_arg, clnt);
	if (result_2 == (listaProductos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	int i=0;
	while(i<CANTIDAD_PRODUCTOS&&result_2->product[i].valor!=0){
		printf("\n		Producto:%s\n	Precio:%f \n",result_2->product[i].nombreIngrediente,result_2->product[i].valor);
		i++;
	}



}


void comprarHamburgesas(){
	printf("\n	Comprar hamburguesas\n\n");
	char respuesta='y';
	do{
		char identificador[MAXNOM];
		printf("\n Digite el identificador de la hamburguesa: ");
		scanf("%s",identificador);
		if(existeHamburguesa(identificador)==-1){
			int incorrecto=0;

			strcpy(registrarpedidosistema_3_arg.pedido_hamburguesas[posBurger].identificador,identificador);
			getchar();
			
			do{
				char tipo='0';
				printf("\n Digite el tipo de hamburguesa p,m,g: ");
				scanf("%c",&tipo);
				getchar();
				
				if(tipo=='m'||tipo=='p'||tipo=='g'){
					(registrarpedidosistema_3_arg).pedido_hamburguesas[posBurger].tipo=tipo;
					incorrecto=0;
				}else{
					printf("\n Tipo incorrecto ingrese nuevamente....");
					incorrecto=1;
					
				}

			}while(incorrecto==1);
			
			do{
				int cantidad;
				printf("\n Digite la cantidad de ingrediente extra: ");
				scanf("%d",&cantidad);
				if(cantidad>=0){
					(registrarpedidosistema_3_arg).pedido_hamburguesas[posBurger].cantidadIngredientesExtra=cantidad;
					incorrecto=0;
				}else{
					printf("\n Cantidad negativa ingrese nuevamente....");
					incorrecto=1;

				}
				
				getchar();

			}while(incorrecto==1);
			
			fflush(stdin);
			registrarpedidosistema_3_arg.pedido_hamburguesas[posBurger].costo=consultarValorBurger((registrarpedidosistema_3_arg).pedido_hamburguesas[posBurger].tipo);
			posBurger++;

			printf("\n Si desea agregar otra hamburguesa precione y/n: ");
			scanf("%c",&respuesta);
		}else{
			getchar();
			printf("\n	Este identificador ya se ha usado intente con otro...");
		}
		
	}while(respuesta == 'y' && posBurger<10);
	return;
	
}

int existeHamburguesa(char *identificador){
	for(int i=0;i<MAX_PEDIDO;i++){
		if(strcmp(identificador, registrarpedidosistema_3_arg.pedido_hamburguesas[i].identificador)==0){
			return i;
		}
	}
	return-1;
}

float consultarValorBurger(char tipo){
	float valor;

	if(tipo=='p'){
		valor = (burgersBase[0].valor);
	}else if(tipo=='m'){
		valor = (burgersBase[1].valor);
	}else if(tipo=='g'){
		valor = (burgersBase[2].valor);
	}
	return valor;
}

void listarBurgersPedidas(){

	if(posBurger==0){
		printf("\n Primero debe registrar una hamburgesa\n\n	");
		return;
	}
	for(int i=0;i<posBurger;i++){
		printf("\n	Hamburgesa (%d): %s \n",(i+1),registrarpedidosistema_3_arg.pedido_hamburguesas[i].identificador);	
		printf("	Tamanio:");

		if(registrarpedidosistema_3_arg.pedido_hamburguesas[i].tipo=='p'){
			printf(" pequenia");
		}else if(registrarpedidosistema_3_arg.pedido_hamburguesas[i].tipo=='m'){
			printf(" mediana");
		}else{
			printf(" grande");
		}
		printf("\n	Ingredientes extra: %d",registrarpedidosistema_3_arg.pedido_hamburguesas[i].cantidadIngredientesExtra);
		printf("\n	Costo: %.1f\n",registrarpedidosistema_3_arg.pedido_hamburguesas[i].costo);
	}
}


void editarHamburguesa(){
	if(posBurger==0){
		printf("\n No hay hamburgesas registradas...\n");
		return;
	}

	char identificador[MAXNOM];
	printf("\n	Ingrese el identificador de la hamburgesa a modificar: ");
	scanf("%s",identificador);

	int posicion=existeHamburguesa(identificador);
	if(posicion==-1){
		printf("\n	Hamburgesa no registrada...");
	}else{
		//imprime la informacion de la hamburgesa
		printf("\n	Hamburgesa : %s \n",registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].identificador);	
		printf("	Tamanio:");

		if(registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].tipo=='p'){
			printf(" pequenia");
		}else if(registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].tipo=='m'){
			printf(" mediana");
		}else{
			printf(" grande");
		}
		printf("\n	Ingredientes extra: %d",registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].cantidadIngredientesExtra);
		printf("\n	Costo: %.1f\n",registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].costo);
		
		//Le pide nuevamente los valores de la hamburguesa
		int incorrecto=0;
		do{
			char identificador[MAXNOM];
			printf("\n Digite el nuevo identificador de la hamburguesa: ");
			scanf("%s",identificador);


			if(existeHamburguesa(identificador)==-1){
				strcpy(registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].identificador,identificador);
				incorrecto=0;
			}else{
				printf("\n Identificador ya existe intente con otro...");
				incorrecto=1;
			}

			getchar();

		}while(incorrecto==1);
		
		char tipo='0';	
		do{
			
			printf("\n Digite el tipo de hamburguesa p,m,g: ");
			scanf("%c",&tipo);

			
				
			if(tipo=='m'||tipo=='p'||tipo=='g'){
				(registrarpedidosistema_3_arg).pedido_hamburguesas[posicion].tipo=tipo;
				incorrecto=0;
			}else{
				printf("\n Tipo incorrecto ingrese nuevamente...");
				incorrecto=1;
					
			}

			getchar();

		}while(incorrecto==1);
			
		do{
			int cantidad;
			printf("\n Digite la cantidad de ingrediente extra: ");
			scanf("%d",&cantidad);
			if(cantidad>=0){
				(registrarpedidosistema_3_arg).pedido_hamburguesas[posicion].cantidadIngredientesExtra=cantidad;
				incorrecto=0;
			}else{
				printf("\n Cantidad negativa ingrese nuevamente....");
				incorrecto=1;
			}
			
			getchar();

			}while(incorrecto==1);
			fflush(stdin);
			registrarpedidosistema_3_arg.pedido_hamburguesas[posicion].costo=consultarValorBurger((registrarpedidosistema_3_arg).pedido_hamburguesas[posicion].tipo);
					
	}	
	return;
}


void eliminarHamburguesa(){	
	if(posBurger==0){
		printf("\n No hay hamburgesas registradas...\n");
		return;
	}

	char identificador[MAXNOM];
	printf("\n	Ingrese el identificador de la hamburgesa a modificar: ");
	scanf("%s",identificador);

	int posicion=existeHamburguesa(identificador);
	if(posicion==-1){
		printf("\n	Hamburgesa no registrada...");
	}else{

		nodo_hamburguesa1 burgerVacia;
		burgerVacia.costo=0;
		registrarpedidosistema_3_arg.pedido_hamburguesas[posicion]=burgerVacia;
		for(int i=posicion;i<(posBurger-1);i++){
			registrarpedidosistema_3_arg.pedido_hamburguesas[i]=registrarpedidosistema_3_arg.pedido_hamburguesas[i+1];
			registrarpedidosistema_3_arg.pedido_hamburguesas[i+1]=burgerVacia;
		}
		posBurger--;
		printf("\n	La hamburguesa se elimino correctamente...");

	}
	return;

}

void mostrarFactura(char *factura){
	
	int numBurgersP=0;
	int numBurgersM=0;
	int numBurgersG=0;
	float valorNeto=0;
	float valorTotal=0;
	float valorIva=0;
	int iva;

	if(posBurger>0){
		for(int i=0;i<posBurger;i++){
			if(registrarpedidosistema_3_arg.pedido_hamburguesas[i].tipo=='p'){
			numBurgersP++;
			}else if(registrarpedidosistema_3_arg.pedido_hamburguesas[i].tipo=='m'){
				numBurgersM++;
			}else{
				numBurgersG++;
			}
		}



		valorNeto=(numBurgersP*burgersBase[0].valor)+(numBurgersM*burgersBase[1].valor)+(numBurgersG*burgersBase[2].valor);
		//Calculo el valor del %IVA

		if(posBurger>=1 && posBurger<=3){
			iva=5;
		}else if(posBurger>=4 && posBurger<=7){
			iva=8;
		} else if(posBurger>=8){
			if(valorNeto>=120000){
				iva=18;
			}else{
				iva=15;
			}
		}

		valorIva=(valorNeto*(iva))/(100);
		
		valorTotal=valorNeto+valorIva;
		//Guardo estos valores en pedido
		registrarpedidosistema_3_arg.valorNeto=valorNeto;
		registrarpedidosistema_3_arg.valorTotal=valorTotal;

		//impresion de la factura
		char buf[12]; 
    	gcvt(numBurgersP, 11, buf); 
		strcat(factura,"Hamburguesas de tipo pequeño:");
		strcat(factura,buf);
		
		gcvt(numBurgersM, 11, buf); 
		strcat(factura,"\nHamburguesas de tipo mediano:");
		strcat(factura,buf);

		gcvt(numBurgersG, 11, buf); 
		strcat(factura,"\nHamburguesas de tipo grande:");
		strcat(factura,buf);


		gcvt(valorNeto, 11, buf); 
		strcat(factura,"\nCosto sin IVA del pedido: $:");
		strcat(factura,buf);

		gcvt(valorIva, 11, buf); 
		strcat(factura,"\nIVA del pedido: $:");
		strcat(factura,buf);

		gcvt(valorTotal, 11, buf); 
		strcat(factura,"\nCosto con IVA del pedido: $ ");
		strcat(factura,buf);


	}else{
		printf("\n	No se han registrado hamburgesas aun...");
	}
	return;

}
void pagarPedido(CLIENT *clnt,char *factura){
	if(pedidoPagado==0){
		bool_t  *result_3;
		result_3 = registrarpedidosistema_3(&registrarpedidosistema_3_arg, clnt);
		if ((result_3 == (bool_t *) NULL)||result_3==0) {
			clnt_perror (clnt, "call failed");
			printf("\n	No se pudo registrar el pedido...");
		}
		pedidoPagado=1;
		printf("\nPedido pagado con exito...");


		FILE* fichero;
		FILE* fichero2; 
		int id=1;
		char buf[7];
		char facturaid[MAXNOM];
		strcpy(facturaid,"factura_");

		//Consulto en que numero de facura voy
		fichero2 = fopen("infoFacturas.txt", "rt");
		if(fichero2 == NULL ) {
			printf("No fue posible crear la factura\n");			
			fclose(fichero2);	
			return;
   		}else{
			char numId[7];
			fgets(numId,6,fichero2);
			id=atoi(numId);
			id++;
			fclose(fichero2);
			fichero2 = fopen("infoFacturas.txt", "wt");
			fprintf (fichero2, "%d", id, 1);
			fclose(fichero2);
			
		}

		
		
		sprintf(buf, "%d", id);
		strcat(facturaid,buf);
    	fichero = fopen(facturaid, "wt");
		if(fichero == NULL ) {
			printf("No fue posible crear la factura\n");
			
			fclose(fichero);	
   		}else{
			fputs(factura, fichero);
			fclose(fichero);	
		}
	}else{
		printf("\n	El pedido ya se pago anteriormente\n");
	}


	

}