/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pedidos.h"
#include <stdio.h>

/**
 *Funcion que se encarga de consultar los valores de las hamburgusas 
 * Entradas: 
 * Salidas:
 */ 
void cargarValoresHamburguesas();
/**
 * funcion void que consulta los datos de la empresa del servidor
 * entradas: CLIENT
 * salidas:
 */
void datosEmpresa(CLIENT *clnt);


/**
 * funcion void que consulta los datos de los productos del servidor
 * entradas: CLIENT
 * salidas:
 */
void datosProductos(CLIENT *clnt);

void
gestion_hamburguesas_3(char *host)
{
	CLIENT *clnt;
	//empresa  *result_1;
	//char *consultarempresa_3_arg;

	//listaProductos  *result_2;
	//char *consultarproductos_3_arg;
	bool_t  *result_3;
	pedido1  registrarpedidosistema_3_arg;

	//Variables locales
	int opcion=0;


//Se intenta la conexion con el servidor pedidos
#ifndef	DEBUG
	clnt = clnt_create (host, gestion_hamburguesas, gestion_hamburguesas_version, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		printf("Error conectando al servidor...\n");
		exit (1);
	}
#endif	/* DEBUG */

	
	//Se imprime el menu de opciones

	do{
		printf("\n-----------Menu de pedidos----------\n");
		printf("1. Mostrar datos de la empresa\n");
		printf("2. Comprar hamburguesa \n");
		printf("3. Modificar compra de haburguesa\n");
		printf("4. Eliminar hamburguesa del pedido\n");
		printf("5. Listar hamburguesas pedidas\n");
		printf("6. Mostrar factura y pagar pedido\n");
		printf("7. Salir\n\n");

		printf("\n Digite opcion: ");
		scanf("\%d", &opcion);

		switch(opcion){
			case 1:
				//consulto la empresa
				printf("	Informacion Empresa\n");
				datosEmpresa(clnt);
				printf("	Informacion de los productos");
				datosProductos(clnt);
			
			break;
			
				//Comprar Hamburguesas
			case 2:
			/*
			break;

			case 3:
				
			break;

			case 4:
				
			break;


			case 5:
				
			break;

			case 6:
				
			break;
			*/
			case 7:
				//Se desconecta del servidor pedidos
				#ifndef	DEBUG
					clnt_destroy (clnt);
				#endif	 /* DEBUG */
				printf("\nAdios cliente...\n");
				break;
			}
				
				
			
			

	}while(opcion!=7);

	
	
	/*
	
	result_3 = registrarpedidosistema_3(&registrarpedidosistema_3_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/


}


int main (int argc, char *argv[]){
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_hamburguesas_3 (host);
exit (0);
}



void datosEmpresa(CLIENT *clnt){

	char *consultarempresa_3_arg;
	empresa  *result_1;

	result_1 = consultarempresa_3((void*)&consultarempresa_3_arg, clnt);
	if (result_1 == (empresa *) NULL) {
		clnt_perror (clnt, "call failed...\n");
		return;
	}

	printf("	Empresa: %s",(result_1)->nombreEmpresa);
	printf("	NIT: %s\n",(result_1)->NIT);



}

void datosProductos(CLIENT *clnt){
	listaProductos  *result_2;
	char *consultarproductos_3_arg;
	result_2 = consultarproductos_3((void*)&consultarproductos_3_arg, clnt);
	if (result_2 == (listaProductos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	int i=0;
	while(i<CANTIDAD_PRODUCTOS&&result_2->product[i].valor!=0){
		printf("\n		Producto:%s\n	Precio:%f \n",result_2->product[i].nombreIngrediente,result_2->product[i].valor);
		i++;
	}



}