/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pedidos.h"

bool_t
xdr_empresa (XDR *xdrs, empresa *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombreEmpresa, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->NIT, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto (XDR *xdrs, producto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombreIngrediente, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listaProductos (XDR *xdrs, listaProductos *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->product, CANTIDAD_PRODUCTOS,
		sizeof (producto), (xdrproc_t) xdr_producto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_hamburguesa1 (XDR *xdrs, nodo_hamburguesa1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->identificador, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->tipo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadIngredientesExtra))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->costo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pedido1 (XDR *xdrs, pedido1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->idPedido))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pedido_hamburguesas, MAX_PEDIDO,
		sizeof (nodo_hamburguesa1), (xdrproc_t) xdr_nodo_hamburguesa1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valorNeto))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valorTotal))
		 return FALSE;
	return TRUE;
}
