/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "pedidos.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

empresa *
consultarempresa_3(void *argp, CLIENT *clnt)
{
	static empresa clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarEmpresa,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_empresa, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

listaProductos *
consultarproductos_3(void *argp, CLIENT *clnt)
{
	static listaProductos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarProductos,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_listaProductos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
registrarpedidosistema_3(pedido1 *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, registrarPedidoSistema,
		(xdrproc_t) xdr_pedido1, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
