/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NOTIFICACIONES_H_RPCGEN
#define _NOTIFICACIONES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_PEDIDO 10

struct nodo_hamburguesa2 {
	char tipo;
	int cantidadIngredientesExtra;
};
typedef struct nodo_hamburguesa2 nodo_hamburguesa2;

struct pedido2 {
	int mesa;
	nodo_hamburguesa2 pedido_hamburguesas[MAX_PEDIDO];
};
typedef struct pedido2 pedido2;

#define notificacion_hamburguesas 0x20000002
#define notificacion_hamburguesas_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define notificarPedidoSistema 1
extern  bool_t * notificarpedidosistema_1(pedido2 *, CLIENT *);
extern  bool_t * notificarpedidosistema_1_svc(pedido2 *, struct svc_req *);
extern int notificacion_hamburguesas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define notificarPedidoSistema 1
extern  bool_t * notificarpedidosistema_1();
extern  bool_t * notificarpedidosistema_1_svc();
extern int notificacion_hamburguesas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_hamburguesa2 (XDR *, nodo_hamburguesa2*);
extern  bool_t xdr_pedido2 (XDR *, pedido2*);

#else /* K&R C */
extern bool_t xdr_nodo_hamburguesa2 ();
extern bool_t xdr_pedido2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NOTIFICACIONES_H_RPCGEN */
