/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "notificaciones.h"

bool_t *
notificarpedidosistema_1_svc(pedido2 *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	printf("\nHa llegado un nuevo pedido para notificar a los cocineros...\n");
	fflush(stdout);
	if (argp==NULL){
		printf("Error me llego un pedido nulo\n");
		fflush(stdout);
		result=0;
		return &result;
	}

	for(int i=0;i<MAX_PEDIDO;i++){
			if(((*argp).pedido_hamburguesas[i].tipo=='m')||
			((*argp).pedido_hamburguesas[i].tipo=='g')||
			((*argp).pedido_hamburguesas[i].tipo=='p')){
				printf("Hamburguesa No (%d)\n",(i+1));
				fflush(stdout);
				printf("	tipo: %c\n",(*argp).pedido_hamburguesas[i].tipo);
				fflush(stdout);
				printf("	ingredientes extra: %d\n",(*argp).pedido_hamburguesas[i].cantidadIngredientesExtra);
				fflush(stdout);
			}
	}
	/*
	if((result_1 == (bool_t *) NULL)||(result_1==0)) {
		printf("Error de conexion con el servidor de notificaciones...");
		clnt_perror (clnt, "call failed");
		fflush(stdout);
		result=0;
	}else{
		printf("Se notifico con exito a los cocineros...");
		result=1;
	}*/
	

	return &result;
}
